### ISSUE TITLE
Test driven development of a script

### ISSUE THREAD

**Issue by osmart** [ARU-Bioinf-IBDS/TDD_script_demonstration#1]
This is a GitHub issue page See [README.md](https://github.com/ARU-Bioinf-IBDS/TDD_script_demonstration/blob/master/README.md) for details

**Comment by osmart** [comment]
In test-driven development, we write the test before writing new functionality.

In this case, let's write simple unit tests for a complement function.

This should have an argument of a DNA string and return its complement as a string

input DNA seq | complement
---------------|--------------
A | T
T | A
G | C
C | G
ATGC | TACG
CAATTTGGGG | GTTAAACCCC

Note that this test is totally separate from the script part. Test the function in isolation.

**Comment by osmart** [comment]
Now let us create a function that will be used to parse the command line arguments. In this case, according to [README.md](https://github.com/ARU-Bioinf-IBDS/TDD_script_demonstration/blob/master/README.md) we need to get a `sequence` and an optional boolean flag `reverse` that will be True if `-reverse` is specified.

Start by working out what do by writing a non-functional stub of function `parse_command_line_args` with a docstring.

**Comment by osmart** [comment]
Can then write unit tests that `parse_command_line_args` works returning the sequence and presence of the `-reverse` flag.

**Comment by osmart** [comment]
Commit e67bd6690 Unit tests for parse_command_line_args they fail as the function not yet written (TDD)

**Comment by osmart** [comment]
Now it is appropriate to convert  `complement.py` into a script by

- [x] adding a standard python shebang
- [x]  Linux `chmod a+x` the file to make it exectutable
- [x] adding a main function that is only invoked "if __name__ == "__main__":" 
       see TW10 webinar for a discussion on this see https://canvas.anglia.ac.uk/courses/12178/discussion_topics/118737 
- [x] add debug printout of sequence and reverse for manual testing.

**Comment by osmart** [comment]
Got script running 5178e7e but help message needs improvement.

So I decide on the help message and add a unit test for this. Testing the help message
involves capturing the script's standard output. This is quite advanced stuff
see https://docs.pytest.org/en/latest/capture.html#accessing-captured-output-from-a-test-function

**Comment by osmart** [comment]
Next step is to connect up the complement function so the script does what it is meant to.

But we are doing TDD so let us first write a 'system test' that running 

$ ./complement A

produces a printout of 'T'

We need to capture stdout again.

**Comment by osmart** [comment]
On reflection rename pytest files to be clearer.

**Comment by osmart** [comment]
Only thing that remains is to implement the -reverse option.
If this is run get ugly NotImplementedError
```
	$ ./complement.py -reverse ATTT
	Traceback (most recent call last):
	  File "./complement.py", line 52, in <module>
	    main()
	  File "./complement.py", line 45, in main
	    raise NotImplementedError('reverse option not yet implemented')
	NotImplementedError: reverse option not yet implemented
```
It is left as a user exercise to do this following TDD. I would recommend 

1.  writing a test for a new function reverse_complement this should fail
2. writing the reverse_complement function.
3. Adding tests with for `-reverse` to the [test_complement_py_script.py](https://github.com/ARU-Bioinf-IBDS/TDD_script_demonstration/blob/master/test_complement_py_script.py#L23) - replacing `TODO`
4. Finally invoking reverse_complement in [complement.py](https://github.com/ARU-Bioinf-IBDS/TDD_script_demonstration/blob/master/complement.py#L45) so that tests pass
5. Manually testing the script.
